# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d0c2941890fa7cd7e67da630e0470ec1e578dd61be6538ad7c93255f13c691f0f2e062fbfbeb0f166544689d4def9e910c7ec7057d10a766bad237c1c5ab9fa

test:
  secret_key_base: 0b138789de3be093220c4cbbc2bf2a9461b5da1f76363aa351e76042d60f85ddeba0789ae71a25ee52c15135f39dc4f7f54f80cce173b7b3fdad141b91583896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
